# Generated by Django 5.1.6 on 2025-04-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_employee_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='reports/')),
                ('is_equipped', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Çalışan Raporu',
                'verbose_name_plural': 'Çalışan Raporları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
