# Generated by Django 5.1.6 on 2025-04-01 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_imageurl'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='employees.employee'),
        ),
    ]
