# Generated by Django 5.1.6 on 2025-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_employeereport_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='missing_equipment',
            field=models.TextField(blank=True, verbose_name='Eksik Ekipmanlar'),
        ),
    ]
