# Generated by Django 5.1.6 on 2025-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_employeereport_missing_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereport',
            name='reported_pozisyon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rapor Anındaki Pozisyon'),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='reported_supervizor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rapor Anındaki Süpervizör'),
        ),
        migrations.AddField(
            model_name='employeereport',
            name='reported_vardiya',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rapor Anındaki Vardiya'),
        ),
    ]
