# Generated by Django 5.1.6 on 2025-03-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sicil_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
