# Generated by Django 5.1.6 on 2025-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_sicil_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='imageUrl',
            field=models.URLField(default='1.jpg', max_length=300),
        ),
    ]
