# Generated by Django 5.1.6 on 2025-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='imageUrl',
            field=models.URLField(default='default.jpg', max_length=300),
        ),
    ]
