# Generated by Django 5.1.6 on 2025-04-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozisyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozisyon_ad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sicil_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pozisyon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.pozisyon'),
        ),
        migrations.CreateModel(
            name='Vardiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardiya_type', models.CharField(choices=[('GECE', 'Gece'), ('GUNDUZ', 'Gündüz')], default='GUNDUZ', max_length=6)),
                ('vardiya_ad', models.CharField(blank=True, max_length=100)),
                ('vardiya_supervizor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_shifts', to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='vardiya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.vardiya'),
        ),
    ]
