# Generated by Django 5.1.6 on 2025-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_pozisyon_alter_employee_age_alter_employee_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='imageUrl',
            field=models.URLField(blank=True, default='default.jpg', max_length=300, null=True),
        ),
    ]
