# Generated by Django 5.1.6 on 2025-04-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_pozisyon_alter_employee_vardiya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vardiya',
            name='vardiya_ad',
        ),
    ]
